[llm]
provider = "openai"
model = "gpt-4o-mini"
api_key_env = "OPENAI_API_KEY"

[fetch]
allow_live_web = true

[execution]
run_mode = "ask"
shell = "/bin/bash"
working_dir = "./.aiops_workspace"
sandbox = "docker"

[session]
persistent_memory = true
max_log_files = 10
max_log_size_mb = 10