[llm]
provider = "openai"
model = "gpt-4o-mini"
api_key_env = "OPENAI_API_KEY"

[execution]
shell = "/bin/bash"
working_dir = "./.aiops_workspace/"
state_file = ".aiops_state.json"
sandbox = "docker"

[session]
persistent_memory = true
max_log_files = 10
max_log_size_mb = 10

[rag]
allow_rag = true
index_path = "./.aiops_workspace/rag_index"
model_name = "all-MiniLM-L6-v2"
similarity_threshold = 0.4